feat(api): Add build creation and upload close #59
Linkvalue/Appbuild pull request #69
Opened 2017-03-12 09:50 UTC by thomasleduc

- [X] Add build creation via API
- [X] Add build file upload via API
- [ ] Create test for the 2 routes
- [ ] Add Generic Authentication on the API
- [ ] Get the filename from query param ?
- [ ] Finish the `curl` in `misc/` to add a build from command line

2017-03-12 10:59 UTC, Oliboy50 requested changes

2017-03-12 10:59 UTC, Oliboy50 commented on src/ApplicationBundle/Service/BuildUploadHelper.php
> +        $filePath = DIRECTORY_SEPARATOR.
ça n'sert à rien d'utiliser la constante `DIRECTORY_SEPARATOR` si au final tu ne cibles que les systèmes UNIX (les chemins de fichiers absolus sur Windows ne commencent pas par `\`)

par contre, tu peux remédier facilement au problème en faisant comme ça :

```php
        $filePath = sys_get_temp_dir() . DIRECTORY_SEPARATOR . ltrim($filename, DIRECTORY_SEPARATOR);
```

> sys_get_temp_dir() returns C:\Windows

2017-03-12 18:49 UTC, thomasleduc commented on src/ApplicationBundle/Service/BuildUploadHelper.php
> +        $filePath = DIRECTORY_SEPARATOR.
Ah cool, merci !
Et pour le filename en query params ça ne parait pas déconnant ? Comme je l'envoie en binary dans le body, je n'ai pas de champ libre pour passer son nom (et son extension). 2 choix : Passer le filename dans le query param ou compute un nom depuis le `build->getLabel` et ajouter l'extension depuis le type de build.

2017-03-12 19:35 UTC, Oliboy50 commented on doc/api/build.md
> +Location: http://domain.com/application/3/build/1/file
tu peux rajouter que la réponse retourne une 200 (dans le cas où ça s'est bien passé)

2017-03-12 19:37 UTC, Oliboy50 commented on doc/api/build.md
> +Note: This route is given by `Create a new build` and can be put on an other domain (like amazon S3).
j'suis pas sûr que `and can be put on an other domain (like amazon S3)` soit bien utile, car cette doc est surtout à destination des utilisateurs de l'API, et ce n'est pas eux qui vont choisir où pointera cette route, eux ils doivent se contenter d'utiliser ce qu'on leur donne

2017-03-12 19:39 UTC, Oliboy50 commented on src/ApplicationBundle/Controller/Api/BuildController.php
> +use Behat\Mink\Exception\Exception;
Behat c'est pour les tests fonctionnels, pas pour le code de prod :)

2017-03-12 19:42 UTC, Oliboy50 commented on src/ApplicationBundle/Controller/Api/BuildController.php
> +use Majora\OTAStore\ApplicationBundle\Controller\Admin\BaseController;
si le controller d'API doit vraiment avoir accès à des méthodes de "Admin\BaseController", alors il faut sortir "BaseController" du dossier "Admin" (sinon, je préfèrerais que tu duppliques le peu de code dont tu as besoin dans un "Api\BaseController" pour éviter au maximum le couplage entre les 2)

2017-03-12 19:45 UTC, Oliboy50 commented on src/ApplicationBundle/Controller/Api/BuildController.php
> -    public function getLatestForApplicationAction(Application $application)
on n'en a plus besoin de cette route d'API ?

2017-03-12 19:48 UTC, Oliboy50 commented on src/ApplicationBundle/Controller/Api/BuildController.php
> +                true
je n'crois pas que `true` marche encore depuis SF3, il faut passer la constante `UrlGeneratorInterface::ABSOLUTE_URL` à la place

2017-03-12 19:50 UTC, Oliboy50 commented on src/ApplicationBundle/Controller/Api/BuildController.php
> +     * Upload application for a build.
Upload build file for an application

2017-03-12 19:54 UTC, Oliboy50 commented on src/ApplicationBundle/Controller/Api/BuildController.php
> +        $response = new Response();
tu peux renvoyer une `JsonResponse` tant qu'à faire, car je sens qu'on va devoir rajouter des champs dans la réponse en json plus tard, genre `"errors": [ "fichier trop gros", "le build n'existe pas" ]`

2017-03-12 19:54 UTC, Oliboy50 commented on src/ApplicationBundle/Controller/Api/BuildController.php
> +     * @return Response
JsonResponse

2017-03-12 19:56 UTC, Oliboy50 commented on src/ApplicationBundle/Controller/Api/BuildController.php
> +         TODO handle de authentication
lol, je sens que ça va être drôle ça 😄

2017-03-12 20:00 UTC, Oliboy50 commented on src/ApplicationBundle/Resources/config/doctrine/Build.orm.yml
> +            nullable: true
je pense que tu vas devoir créer un fichier de migration pour jouer cette requête SQL du coup

voilà la manip (ça va te remettre les data par défaut de l'env de dev par contre) : 
```
make db-rebuild db-update db-build
```

ça devrait te créer un fichier DoctrineMigration que tu devras commit

2017-03-12 20:02 UTC, Oliboy50 commented on src/ApplicationBundle/Resources/config/routing/api/application_build.yml
> +    methods:  [GET, HEAD]
tu as supprimé le code de cette route par contre dans le controller x)

2017-03-12 20:07 UTC, Oliboy50 commented on src/ApplicationBundle/Service/BuildUploadHelper.php
> +     * @param File|UploadedFile $uploadedFile
laisse que `File` comme type, vu que `UploadedFile` hérite de `File`, pas besoin d'indiquer qu'on prend les 2

2017-03-12 20:11 UTC, Oliboy50 commented on src/ApplicationBundle/Controller/Api/BuildController.php
> +    private function processForm(Request $request, FormInterface $form)
pas besoin de créer une méthode de 2 lignes si elle n'est utilisée qu'à un seul endroit :) (KISS)

2017-03-12 20:19 UTC, Oliboy50 commented on src/ApplicationBundle/Controller/Api/BuildController.php
> +            if ($e instanceof FileException) {
symfony va renvoyer une 500 de toute façon si le code throw une Exception, donc tu peux enlever tout le `try / catch` 

sauf si tu voulais renvoyer une `JsonResponse` avec un message d'erreur en json, ce qui est une très bonne idée, dans ce cas, tu devrais plutôt faire ton catch comme ça : 
```php
catch (FileException $e) {
    return new JsonResponse(['errors' => ['Cannot upload this file.']], 500);
}
```

2017-03-12 20:55 UTC, Oliboy50 commented on src/ApplicationBundle/Controller/Api/BuildController.php
> +            $tmpFile = $uploadHelper->createTempFile($request->getContent(), $filename);
en relisant, j'viens de comprendre ce que faisait ce code, sorry

donc en fait, ce que tu as fait c'est un bon exemple d'upload en PHP pur, mais la façon "Symfony" pour faire de l'upload, c'est comme ça : 
```php
$tmpFile = $request->files->get('build_file'); // si tu veux vraiment que la requête ne contienne que le fichier comme body, alors tu ne pourras probablement pas utiliser `get()` met tu devrais pouvoir faire `$request->files->all()[0]` je pense
```

(je l'ai fait ici par exemple en multipart/form-data : https://github.com/LinkValue/MajoraOTAStore/blob/master/src/ApplicationBundle/Controller/Admin/BuildController.php#L251)

comme ça, t'as même pas besoin de t'embêter avec le `filename` puisque le fichier uploadé conservera son nom, et t'as plus besoin de la méthode `createTempFile` non plus

2017-03-12 20:58 UTC, Oliboy50 commented on src/ApplicationBundle/Service/BuildUploadHelper.php
> +        $filePath = DIRECTORY_SEPARATOR.
désolé, j'avais mal lu le code la première fois, au final, tu n'as pas besoin de cette méthode, j'ai expliqué ici : https://github.com/LinkValue/MajoraOTAStore/pull/69#discussion_r105568668
comment laisser Symfony faire le boulot à ta place

2017-03-12 21:02 UTC, Oliboy50 commented
c'est du bon boulot, impressionnant pour qqun qui fait rarement du PHP et très sympa de ta part de participer 👍

2017-03-13 07:47 UTC, thomasleduc commented on src/ApplicationBundle/Controller/Api/BuildController.php
> +            $tmpFile = $uploadHelper->createTempFile($request->getContent(), $filename);
Ahhh j'avais essayé avec $request->files mais c'était galère. Je vais regarder si c'est possible avec `$request->files->all()[0]` mais à mon avis sans multipart de toute façon, on aura pas le nom du fichier.

2017-03-13 07:47 UTC, thomasleduc commented on src/ApplicationBundle/Controller/Api/BuildController.php
> +    private function processForm(Request $request, FormInterface $form)
👍

2017-03-13 07:48 UTC, thomasleduc commented on src/ApplicationBundle/Service/BuildUploadHelper.php
> +     * @param File|UploadedFile $uploadedFile
Ouai je me suis demandé mais pour la compréhension de l'update que j'apportais, je me suis dit que ça pouvait être utile. Mais ok ;)

2017-03-13 07:50 UTC, thomasleduc commented on src/ApplicationBundle/Resources/config/doctrine/Build.orm.yml
> +            nullable: true
Rahh merci ! J'ai essayé de le créer mais j'ai pas réussi, du coup j'ai fait un `php bin/console doctrine:schema:update --force` mais je me doutais que c'était crade ^^

2017-03-13 07:55 UTC, thomasleduc commented on src/ApplicationBundle/Controller/Api/BuildController.php
> +use Majora\OTAStore\ApplicationBundle\Controller\Admin\BaseController;
👍

2017-03-13 07:56 UTC, thomasleduc commented on doc/api/build.md
> +Note: This route is given by `Create a new build` and can be put on an other domain (like amazon S3).
Ok mais c'est pour dire que l'url renvoyée, n'est pas forcément un endpoint de l'API.

2017-03-13 08:00 UTC, thomasleduc commented on doc/api/build.md
> +Location: http://domain.com/application/3/build/1/file
Je vais le changer de toute façon, c'est trop galère de changer le header Location, et ça n'a pas vraiment de sens. Dans le code, je retourne un json avec build id et url to upload

2017-03-13 08:02 UTC, thomasleduc commented on doc/api/build.md
> +Location: http://domain.com/application/3/build/1/file
Postman et les clients js (si pas interceptés) se font redirigés automatiquement avec `Location`.

2017-03-13 09:43 UTC, thomasleduc commented
j'ai fait les modifs au fait. Il me manque juste celle là : `$request->files->all()[0]`. Je regarderai si elle permet bien de récupérer le body content en file et si elle permet de chopper le nom.
Pour l'autentification, on est d'accord qu'il n'y a rien aujourd'hui sur l'API et qu'il va falloir faire un jolie middleware à la symfony et pas juste une fonction de check ? :)

2017-03-13 19:48 UTC, Oliboy50 commented
@thomasleduc d'après @JMLamodiere la bonne façon de faire serait `$request->files->get(0)`, et si ça ne marche pas, tu auras toujours `all()[0]` qui (j'espère) devrait fonctionner... c'est en grande partie pour ce genre de cas qu'on utilise un framework, donc ça serait dommage qu'on doive tout faire soi-même 😿

2017-03-13 19:56 UTC, Oliboy50 commented on src/ApplicationBundle/Controller/Api/BuildController.php
> +        $form->submit($data);
il manque une petite validation des données avant d'enregistrer le nouveau build en bdd : 

```
$form->submit($data);

if ($form->isSubmitted() && $form->isValid()) {
    $em = $this->container->get('doctrine.orm.entity_manager');
    ...
}

return new JsonResponse(...);
```

2017-03-13 20:04 UTC, Oliboy50 commented on src/ApplicationBundle/Controller/Api/BuildController.php
> +            $tmpFile = $uploadHelper->createTempFile($request->getContent(), $filename);
si tu pourras avoir le nom du fichier à partir de l'UploadedFile que `$request->files->get(0)` te renverras, comme ça : 
```php
$filename = $uploadHelper->generateFilename($tmpFile);
```

voir ce que j'avais fait pour l'upload en ajax : https://github.com/LinkValue/MajoraOTAStore/blob/master/src/ApplicationBundle/Controller/Admin/BuildController.php#L260

2017-03-13 20:08 UTC, Oliboy50 commented on src/ApplicationBundle/Controller/Api/BuildController.php
> +            throw $e;
tu peux remplacer ton `catch if throw` par : 
```php
} catch (FileException $e) {
    return new JsonResponse(['errors' => ['Cannot upload this file.']], 500);
}
```

2017-03-29 14:38 UTC, thomasleduc commented on src/ApplicationBundle/Controller/Api/BuildController.php
> +        $form->submit($data);
$form->isSubmitted(), ce n'est pas pour dire :
- Soit je render mon formulaire
- Soit je dois le traiter
?

2017-03-29 14:38 UTC, thomasleduc commented on src/ApplicationBundle/Controller/Api/BuildController.php
> +            throw $e;
done

2017-05-21 19:05 UTC, Oliboy50 requested changes
quelques petites corrections mineures, il faut aussi que tu recréés le fichier `var/cache/.gitkeep` (c'est un fichier vide qui permet de conserver la structure du dossier de cache)

2017-05-21 19:05 UTC, Oliboy50 commented on doc/api/build.md
> +## Create a new build (WIP)
toujours WIP ?

2017-05-21 19:05 UTC, Oliboy50 commented on CONTRIBUTING.md
> +### Get a token (WIP)
toujours WIP ?

2017-05-21 19:05 UTC, Oliboy50 commented on doc/api/build.md
> +## Upload a file for a build (WIP)
toujours WIP ?

2017-05-21 19:05 UTC, Oliboy50 commented on doc/api/build.md
> +PUT /api/build/{build_id}/file
j'pense qu'il faut mettre `PUT upload_location.from.create_a_new_build.request` (parce qu'il ne faut pas se fier à cette route, le domaine peut changer)

2017-05-21 19:05 UTC, Oliboy50 commented on doc/api/build.md
> +Note: This route is generally given by `Create a new build`.
[...] is always returned by [...] through `upload_location` response parameter

2017-05-21 19:05 UTC, Oliboy50 commented on src/ApplicationBundle/Controller/Api/BuildController.php
> +        $form->submit($data);
il manque toujours cette vérification, après avoir submit le formulaire : 

```php
if (!$form->isValid()) {
    return new JsonResponse(null, 400);
}
```

sinon tu risques de persister des data invalides en bdd...
on verra dans un second temps pour renvoyer la liste des erreurs de validations

2017-05-25 12:47 UTC, thomasleduc commented on src/ApplicationBundle/Controller/Api/BuildController.php
> +         TODO handle de authentication
Pour l'instant seul les admins ont le droit d'uplaod. Dans une V2, il faudrait avoir un mapping des droits application/user sur la création de build.

2017-05-25 12:50 UTC, thomasleduc commented on src/ApplicationBundle/Controller/Api/BuildController.php
> +        $form->submit($data);
👍

2017-05-25 20:15 UTC, Oliboy50 commented on src/ApplicationBundle/Form/Type/BuildAPIType.php
> +        $resolver->setDefaults([
fais plutôt comme ça : 
```php
    parent::configureOptions($resolver);
    $resolver->setDefault('csrf_protection', false);
```

pour n'overrider qu'une seule chose

2017-05-25 22:56 UTC, thomasleduc commented on src/ApplicationBundle/Form/Type/BuildAPIType.php
> +        $resolver->setDefaults([
yes ! comme c'était une solution temporaire, j'avais pas creusé. Mais carrément. Je le change demain.

2017-05-29 17:49 UTC, Oliboy50 approved these changes

2017-05-31 21:24 UTC, merged